import { useState, useEffect } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { useAuthStore } from '../store/authStore'
import {
  ArrowLeft,
  Clock,
  Users,
  FileText,
  CheckSquare,
  Download,
  ChevronDown,
  ChevronUp,
  Copy,
  Check,
  Loader
} from 'lucide-react'
import axios from 'axios'

export const MeetingSummary = () => {
  const navigate = useNavigate()
  const { meetingId } = useParams()
  const { user } = useAuthStore()

  const [summaryData, setSummaryData] = useState(null)
  const [actionItems, setActionItems] = useState([])
  const [showTranscript, setShowTranscript] = useState(false)
  const [copied, setCopied] = useState(false)
  const [loading, setLoading] = useState(true)
  const { token } = useAuthStore()

  useEffect(() => {
    const fetchSummary = async () => {
      try {
        const res = await axios.get(`/api/summaries/${meetingId}`, {
          headers: { Authorization: `Bearer ${token}` }
        })
        const data = res.data
        if (data) {
          setSummaryData(data)
          setActionItems(data.actionItems || [])
        }
      } catch (error) {
        console.error('Error fetching summary:', error)
      } finally {
        setLoading(false)
      }
    }
    fetchSummary()
  }, [meetingId, token])

  const toggleAction = (id) => {
    setActionItems((prev) =>
      prev.map((item) =>
        item.id === id ? { ...item, done: !item.done } : item
      )
    )
  }

  const handleCopy = async () => {
    try {
      if (summaryData?.summary) {
        await navigator.clipboard.writeText(summaryData.summary)
        setCopied(true)
        window.setTimeout(() => setCopied(false), 2000)
      }
    } catch (error) {
      console.error('Copy failed', error)
    }
  }

  const handleBack = () => {
    navigate('/dashboard')
  }

  return (
    <div className="min-h-screen bg-[#FAF9F7]">
      <div className="border-b border-[#E8E4DD] bg-white px-6 py-4 flex items-center justify-between">
        <div className="flex items-center gap-2 text-[#1A1A1A] font-semibold">
          <span className="text-[#7C3AED]">●</span>
          IntellMeet
        </div>
        <button
          onClick={handleBack}
          className="flex items-center gap-2 text-sm text-[#6B6560] hover:text-[#1A1A1A] transition"
        >
          <ArrowLeft size={16} />
          Back to dashboard
        </button>
      </div>

      <div className="max-w-4xl mx-auto px-6 pt-6 pb-10">
        {loading || !summaryData ? (
          <div className="flex items-center justify-center py-20 text-[#6B6560]">
            <Loader className="animate-spin mr-2" />
            Loading summary...
          </div>
        ) : (
          <>
            <div className="pb-6 border-b border-[#E8E4DD]">
              <h1 className="text-2xl font-semibold text-[#1A1A1A]">{summaryData.title}</h1>
          <div className="flex flex-wrap gap-4 mt-3">
            <span className="bg-white border border-[#E8E4DD] text-[#6B6560] text-xs px-3 py-1.5 rounded-full flex items-center gap-1.5">
              {summaryData.date}
            </span>
            <span className="bg-white border border-[#E8E4DD] text-[#6B6560] text-xs px-3 py-1.5 rounded-full flex items-center gap-1.5">
              <Clock size={14} />
              {summaryData.duration || '0 minutes'}
            </span>
            <span className="bg-white border border-[#E8E4DD] text-[#6B6560] text-xs px-3 py-1.5 rounded-full flex items-center gap-1.5">
              <Users size={14} />
              {summaryData.participants?.length || 0} participants
            </span>
          </div>
        </div>

        <div className="grid grid-cols-3 gap-5 mt-6 items-start">
          <div className="col-span-2 space-y-5">
            <div className="bg-white border border-[#E8E4DD] rounded-2xl p-5">
              <div className="flex items-center justify-between gap-4 pb-3 border-b border-[#E8E4DD] mb-0">
                <div className="flex items-center gap-2 text-sm font-semibold text-[#1A1A1A]">
                  <span>AI Summary</span>
                  <FileText size={16} className="text-[#7C3AED]" />
                </div>
                <button
                  onClick={handleCopy}
                  className="flex items-center gap-2 text-xs text-[#6B6560] hover:text-[#1A1A1A] transition"
                >
                  {copied ? <Check size={14} /> : <Copy size={14} />}
                  {copied ? 'Copied' : 'Copy summary'}
                </button>
              </div>
              <p className="text-sm text-[#6B6560] leading-relaxed pt-3">
                {summaryData.summary}
              </p>
              <div className="bg-[#7C3AED]/8 text-[#7C3AED] text-xs px-2.5 py-1 rounded-full inline-flex items-center gap-1 mt-4">
                ✦ Generated by AI
              </div>
            </div>

            <div className="bg-white border border-[#E8E4DD] rounded-2xl p-5">
              <div className="flex items-center justify-between gap-3 pb-3 border-b border-[#E8E4DD]">
                <div className="flex items-center gap-2 text-sm font-semibold text-[#1A1A1A]">
                  <CheckSquare size={16} className="text-[#7C3AED]" />
                  Action Items
                </div>
                <span className="bg-[#F5F2EE] text-[#6B6560] text-xs px-2 py-0.5 rounded-full">
                  {actionItems.length}
                </span>
              </div>
              <div className="mt-0 space-y-3">
                {actionItems.map((item) => (
                  <div
                    key={item.id}
                    className="flex items-start gap-3 py-3 border-b border-[#E8E4DD] last:border-0"
                  >
                    <button
                      type="button"
                      onClick={() => toggleAction(item.id)}
                      className={`w-5 h-5 rounded-full flex-shrink-0 mt-0.5 cursor-pointer flex items-center justify-center ${
                        item.done
                          ? 'bg-[#7C3AED]'
                          : 'border-2 border-[#E8E4DD] hover:border-[#7C3AED]'
                      }`}
                    >
                      {item.done && <Check size={12} className="text-white" />}
                    </button>
                    <div className="min-w-0 flex-1">
                      <p className={`text-sm ${item.done ? 'line-through text-[#6B6560]' : 'text-[#1A1A1A]'}`}>
                        {item.task}
                      </p>
                      <p className="text-xs text-[#6B6560] mt-1">
                        {item.assignee} · Due {item.due}
                      </p>
                    </div>
                    <span
                      className={`text-xs px-2 py-0.5 rounded-full ${
                        item.done
                          ? 'bg-[#F5F2EE] text-[#6B6560]'
                          : 'bg-[#FEF3C7] text-[#D97706]'
                      }`}
                    >
                      {item.due}
                    </span>
                  </div>
                ))}
              </div>
            </div>

            <div className="bg-white border border-[#E8E4DD] rounded-2xl overflow-hidden">
              <button
                type="button"
                onClick={() => setShowTranscript((prev) => !prev)}
                className="w-full flex items-center justify-between px-5 py-4 hover:bg-[#F5F2EE] transition"
              >
                <span className="text-sm font-semibold text-[#1A1A1A]">Transcript</span>
                {showTranscript ? (
                  <ChevronUp size={18} className="text-[#6B6560]" />
                ) : (
                  <ChevronDown size={18} className="text-[#6B6560]" />
                )}
              </button>
              {showTranscript && (
                <div className="px-6 pb-6 space-y-4">
                  {summaryData.transcript?.map((line, index) => (
                    <div key={index}>
                      <div className="flex items-center gap-3 mb-2">
                        <span className="text-xs font-semibold text-[#7C3AED]">
                          {line.speaker}
                        </span>
                        <span className="text-xs text-[#6B6560]">{line.time}</span>
                      </div>
                      <p className="text-sm text-[#1A1A1A]">{line.text}</p>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>

          <div className="col-span-1 space-y-4 sticky top-4">
            <div className="bg-white border border-[#E8E4DD] rounded-2xl p-4">
              <h2 className="text-sm font-semibold text-[#1A1A1A] mb-3">Participants</h2>
              <div className="space-y-3">
                {summaryData.participants?.map((participant) => (
                  <div key={participant} className="flex items-center gap-3 py-2">
                    <div className="w-8 h-8 rounded-full bg-[#7C3AED]/10 text-[#7C3AED] text-xs font-semibold flex items-center justify-center">
                      {participant
                        .split(' ')
                        .map((item) => item[0])
                        .join('')}
                    </div>
                    <div>
                      <p className="text-sm text-[#1A1A1A]">{participant}</p>
                      {participant === 'You' ? (
                        <p className="text-xs text-[#6B6560]">You</p>
                      ) : null}
                    </div>
                  </div>
                ))}
              </div>
            </div>

            <div className="bg-white border border-[#E8E4DD] rounded-2xl p-4">
              <h2 className="text-sm font-semibold text-[#1A1A1A] mb-3">Meeting details</h2>
              <div className="space-y-3 text-sm">
                <div>
                  <p className="text-xs text-[#6B6560]">Meeting ID</p>
                  <p className="font-medium text-[#1A1A1A] font-mono">{meetingId}</p>
                </div>
                <div>
                  <p className="text-xs text-[#6B6560]">Date</p>
                  <p className="font-medium text-[#1A1A1A]">{summaryData.date}</p>
                </div>
                <div>
                  <p className="text-xs text-[#6B6560]">Duration</p>
                  <p className="font-medium text-[#1A1A1A]">{summaryData.duration || '0 minutes'}</p>
                </div>
              </div>
            </div>

            <button
              type="button"
              onClick={() => window.print()}
              className="w-full mt-1 bg-[#7C3AED] hover:bg-[#6D28D9] text-white rounded-xl py-2.5 text-sm font-semibold transition flex items-center justify-center gap-2"
            >
              <Download size={16} />
              Export Summary
            </button>
          </div>
        </div>
        </>
        )}
      </div>
    </div>
  )
}
